config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  root to: "meetings#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :meeting_rooms do
    get :available, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
require 'google/api_client'

class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :meeting_room

  validates_presence_of :start_time, :end_time, :meeting_room
  validate :end_time_after_start_time!
  validate :meeting_room_available!

  after_create :create_google_event

  scope :for_day, -> (date = Date.today) do
    where("start_time BETWEEN ? AND ?", date.to_date.beginning_of_day, date.to_date.end_of_day)
  end

  def meeting_room_available!
    return unless start_time && end_time
    if !meeting_room.available?(start_time, end_time)
      errors.add(:meeting_room_id, "#{meeting_room.name} isn't availble at this time.")
    end
  end

  def end_time_after_start_time!
    return unless start_time && end_time
    if end_time < start_time
      errors.add(:end_time, "Me must be after start time")
    end
  end

  def create_google_event
    return if user.token.empty?

    @event = {
      "summary" => "A new meeting",
      "description" => "meeting in #{meeting_room.try(:name)}",
      "location" => "Location",
      "start" => { "dateTime" => start_time.rfc3339 },
      "end" => { "dateTime" => end_time.rfc3339 },
      "attendees" => [ { "email" => "#{user.email}" }]
    }

    client = Google::APIClient.new
    client.authorization.access_token = user.token
    service = client.discovered_api("calendar", "v3")

    @set_event = client.execute(:api_method => service.events.insert,
                                :parameters => {"calendarId" => user.email, "sendNotifications" => true},
                                :body => JSON.dump(@event),
                                :headers => {"Content-Type" => "application/json"})

  end
end

app/models/meeting_room.rb
class MeetingRoom < ApplicationRecord
  has_many :meetings

  validates_uniqueness_of :name

  def available?(start_time, end_time)
    Meeting.where("meeting_room_id = ? AND start_time BETWEEN ? AND ?", self.id, start_time, end_time).empty?
  end

  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :meetings

  def to_s
    name
  end

  def self.find_for_google_oauth2(access_token)
    data = access_token.info
    user = User.find_by(email: data.email)
    if user
      user.provider = access_token.provider
      user.uid = access_token.uid
      user.token = access_token.credentials.token
      user.save
      user
    else
      User.create(email: data.email, name: data.name, provider: access_token.provider, uid: access_token.uid, token: access_token.credentials.token)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  before_action :set_meeting_room, only: [:show, :edit, :update, :destroy]

  # GET /meeting_rooms
  # GET /meeting_rooms.json
  def index
    @meeting_rooms = MeetingRoom.all
  end

  # GET /meeting_rooms/1
  # GET /meeting_rooms/1.json
  def show
  end

  # GET /meeting_rooms/new
  def new
    @meeting_room = MeetingRoom.new
  end

  # GET /meeting_rooms/1/edit
  def edit
  end

  # POST /meeting_rooms
  # POST /meeting_rooms.json
  def create
    @meeting_room = MeetingRoom.new(meeting_room_params)

    respond_to do |format|
      if @meeting_room.save
        format.html { redirect_to @meeting_room, notice: 'Meeting room was successfully created.' }
        format.json { render :show, status: :created, location: @meeting_room }
      else
        format.html { render :new }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meeting_rooms/1
  # PATCH/PUT /meeting_rooms/1.json
  def update
    respond_to do |format|
      if @meeting_room.update(meeting_room_params)
        format.html { redirect_to @meeting_room, notice: 'Meeting room was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting_room }
      else
        format.html { render :edit }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_rooms/1
  # DELETE /meeting_rooms/1.json
  def destroy
    @meeting_room.destroy
    respond_to do |format|
      format.html { redirect_to meeting_rooms_url, notice: 'Meeting room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def available
    @meeting_rooms = MeetingRoom.available(nil, nil)
    render json: @meeting_rooms
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting_room
      @meeting_room = MeetingRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_room_params
      params.require(:meeting_room).permit(:number_of_persons, :name)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meeting_rooms = MeetingRoom.all
    @meeting = Meeting.new

    @date = params[:date] || Date.today.to_s
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user = current_user

    respond_to do |format|
      if @meeting.save
        flash[:notice] = "Succesfully create a new event."
        format.js { render :show, status: :created, location: @meeting }
      else
        format.js { render :show, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:user_id, :meeting_room_id, :start_time, :end_time)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"])

    if @user
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      redirect_to new_user_session_path, notice: 'Access Denied'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_list(model)
    return "" unless model.errors.any?
    rvalue = ""
    model.errors.full_messages.each do |m|
      rvalue = "<p class='alert alert-warning' role='alert'>#{m}</p>"
    end
    rvalue
  end
end

app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def draw_meeting_grid(meeting)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetingrooms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navigation" %>

    <div class="container content-wrapper">

      <div class="flashes">
        <% if notice %>
          <p class="alert alert-info" role="alert"><%= notice %></p>
        <% end %>

        <% if alert %>
          <p class="alert alert-warning" role= "alert"><%= alert %></p>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/meeting_rooms/_form.html.erb
<%= form_for(meeting_room) do |f| %>
  <% if meeting_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting_room.errors.count, "error") %> prohibited this meeting_room from being saved:</h2>

      <ul>
      <% meeting_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :number_of_persons %>
    <%= f.text_field :number_of_persons, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/meeting_rooms/edit.html.erb
<h1>Editing Meeting Room</h1>

<%= render 'form', meeting_room: @meeting_room %>

<%= link_to 'Show', @meeting_room %> |
<%= link_to 'Back', meeting_rooms_path %>

app/views/meeting_rooms/index.html.erb
<h1>Meeting Rooms</h1>

<table class="table">
  <thead>
    <tr>
      <th>Number of persons</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meeting_rooms.each do |meeting_room| %>
      <tr>
        <td><%= meeting_room.number_of_persons %></td>
        <td><%= meeting_room.name %></td>
        <td><%= link_to 'Show', meeting_room %></td>
        <td><%= link_to 'Edit', edit_meeting_room_path(meeting_room) %></td>
        <td><%= link_to 'Destroy', meeting_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting Room', new_meeting_room_path %>

app/views/meeting_rooms/new.html.erb
<h1>New Meeting Room</h1>

<%= render 'form', meeting_room: @meeting_room %>

<%= link_to 'Back', meeting_rooms_path %>

app/views/meeting_rooms/show.html.erb
<p>
  <strong>Number of persons:</strong>
  <%= @meeting_room.number_of_persons %>
</p>

<p>
  <strong>Name:</strong>
  <%= @meeting_room.name %>
</p>

<%= link_to 'Edit', edit_meeting_room_path(@meeting_room) %> |
<%= link_to 'Back', meeting_rooms_path %>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <% meeting.errors.full_messages.each do |message| %>
        <p class="alert alert-danger" role= "alert"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :meeting_room_id %>
    <%= form.select(:meeting_room_id, MeetingRoom.all.collect { |mr| [mr.name, mr.id] }, {}, { id: :meeting_meeting_room_id, class: "form-control select2" })  %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <div class='input-group date datepicker'>
      <%= form.text_field :start_time, id: :meeting_start_time, class: "form-control"  %>
      <div class="input-group-addon" style="width: 2.6rem">
        <i class="fa fa-calendar"></i>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <div class='input-group date datepicker'>
      <%= form.text_field :end_time, id: :meeting_end_time, class: "form-control" %>
      <div class="input-group-addon" style="width: 2.6rem">
        <i class="fa fa-calendar"></i>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/meetings/_remote_form.html.erb
<%= form_with(model: @meeting) do |form| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <% @meeting.errors.full_messages.each do |message| %>
        <p class="alert alert-danger" role= "alert"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :meeting_room_id %>
    <%= form.select(:meeting_room_id, MeetingRoom.all.collect { |mr| [mr.name, mr.id] }, {}, { id: :meeting_meeting_room_id, class: "form-control select2" })  %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <div class='input-group date datepicker'>
      <%= form.text_field :start_time, id: :meeting_start_time, class: "form-control"  %>
      <div class="input-group-addon" style="width: 2.6rem">
        <i class="fa fa-calendar"></i>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <div class='input-group date datepicker'>
      <%= form.text_field :end_time, id: :meeting_end_time, class: "form-control" %>
      <div class="input-group-addon" style="width: 2.6rem">
        <i class="fa fa-calendar"></i>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/meetings/_room_day.html.erb
<div class="day-wrapper", id="<%= "#{dom_id(room)}-#{day}" %>">
  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= room.name %>
    </div>
    <div class="col col col-sm-1 col-md-1 col-lg-1 hour-col">0</div>
    <div class="col meeting-col" data-meeting-hour='0'></div>
  </div>

  <% (1..24).each_with_index do |c| %>
    <div class="row">
      <div class="col-sm-4 col-md-4 col-lg-4"></div>
      <div class="col col-sm-1 col-md-1 col-lg-1 hour-col">
        <%= c %>
      </div>
      <div class="col meeting-col" data-meeting-hour='<%= c %>'>
      </div>
    </div>
  <% end %>
</div>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<% date = Date.parse(@date) %>

<h1>Meetings</h1>
<h2><%= l(date) %></h2>
<div class="container meeting-room-overview">
    <div class="row">
      <% @meeting_rooms.each do |meeting_room| %>
        <div id="<%= dom_id(meeting_room) %>" class="col col-xs-4 col-sm-4 col-md-4 col-lg-4 meeting-day-detail">
          <%= render "room_day", day: date, room: meeting_room %>
        </div>
      <% end %>
    </div>
</div>

<div class="row">
  <div class="col">
    <%= link_to((date - 1.days).to_s, meetings_path(date: date - 1.days)) %>
  </div>
  <div class="col text-right">
    <%= link_to((date + 1.days).to_s, meetings_path(date: date + 1.days)) %>
  </div>
</div>

<br>

<%= render partial: "remote_form" %>

<% @meeting_rooms.each do |meeting_room| %>
  <script type="text/javascript">
    <% meetings = meeting_room.meetings.for_day(date).collect do |m|
        { start_hour: m.start_time.hour,
          start_min: m.start_time.min,
          end_hour: m.end_time.hour,
          end_min: m.end_time.min,
          date: m.start_time.to_date}
        end
      %>

    var meetings = <%= meetings.to_json.html_safe %>
    MeetingRoomApp.drawMeetings('<%= dom_id(meeting_room) %>', meetings)
  </script>
<% end %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p>
  <strong>User:</strong>
  <%= @meeting.user %>
</p>

<p>
  <strong>Meeting room:</strong>
  <%= @meeting.meeting_room %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/show.js.erb
$(".flashes").html("");
$(".flashes").html("<%= error_list(@meeting).html_safe %>");

<% if flash[:notice] %>
  $(".flashes").html("<p class='alert alert-info' role='alert'><%= flash[:notice] %></p>");
<% end %>

<%
  meeting = {
    start_hour: @meeting.start_time.hour,
    start_min: @meeting.start_time.min,
    end_hour: @meeting.end_time.hour,
    end_min: @meeting.end_time.min,
    date: @meeting.start_time.to_date
  }
%>

<% unless @meeting.errors.any? %>
  var meeting = <%= meeting.to_json.html_safe %>;
  MeetingRoomApp.drawMeeting("<%= dom_id(@meeting.meeting_room) %>", meeting, meeting.date);
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Brand -->
    <%= link_to "Overview", :root, class: "navbar-brand" %>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="nav-content">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Meeting rooms", :meeting_rooms, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Meetings", :meetings, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: "nav-link")  %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>